### ISSUE TITLE
Support for dataclasses and / or objects with simple attributes

### ISSUE THREAD

**Issue by berendkleinhaneveld** [Korijn/observ#103]
We might want to consider adding support for dataclasses and/or attributes of objects. Or maybe provide an API to make certain attributes 'reactive' for custom classes/objects. 

If we decide against it, this can be a trace of that decision :)

**Comment by Korijn** [comment]
> an API to make certain attributes 'reactive'

I think we already offer that! :)

The one thing that's still missing is a `ref` which is essentially a reactive container for a single plain value.

Can you be more specific about what kind of use cases you have in mind?

**Comment by berendkleinhaneveld** [comment]
> I think we already offer that! :)

Ah, you mean `computed`? I guess that's right, as long as the underlying data is an observ proxy (dict, list, set).

What I mean to say is that we could also support the creation of proxies from dataclass objects, next to dicts, lists and sets. And maybe even normal objects as well, with some caveats/restrictions e.g. limited to 'simple' public attributes or something.

```python
@dataclass
class Foo:
    bar: int

foo = reactive(Foo(bar=0))
watcher = watch(foo, ...)
...
# or maybe even with a decorator:
@reactivedata
@dataclass
class Foo:
    bar: int
```

> The one thing that's still missing is a ref which is essentially a reactive container for a single plain value.

That might also be nice have indeed.

**Comment by Korijn** [comment]
How about:

```py
@dataclass
class Foo:
    bar: ref[int]
    baz: reactive[list[int]]
```

And we could offer a decorator, then this would be equivalent to the above:

```py
@reactive
@dataclass
class Foo:
    bar: int
    baz: list[int]
```
