### ISSUE TITLE
Reactive plain value container

### ISSUE THREAD

**Issue by Korijn** [Korijn/observ#104]
Like `ref` in Vue.

I guess it's just the following under the hood:

```py
def ref(value):
    return reactive({"value": value})
```

We could support dot notation if we make it into a class, something like:

```py
class ref:
    def __init__(self, value):
        self._value = reactive({"value": value})

    @property
    def value(self):
        return self._value["value"]

    # and a setter
```

Which is related to #103

**Comment by berendkleinhaneveld** [comment]
Don't forget the `__slots__` attribute ;)

**Comment by Korijn** [comment]
I think I finally get the name "ref", it's a proxy for a single reference to a value.

**Comment by Korijn** [comment]
https://github.com/vuejs/vue/blob/81598ea2f3bdbc81ae50f2fa9b9e547efc6b6261/src/v3/reactivity/ref.ts#L65

Indeed it's just a proxied dict with a value key
