### ISSUE TITLE
missing type hints for the public API

### ISSUE THREAD

**Issue by ju1ius** [Korijn/observ#110]
Hi,

The publis API does not have type hints ATM, which leads to a bad experience when using the library.

For example, the following expression:
```py
state = reactive({'value': 0})
```
is inferred as `Proxy | Any | tuple[Any, ...]`, so when trying to do this:
```py
state['value'] = 42
```
we get the following error: `"__getitem__" method not defined on type "Proxy"`.

Typescript [gets away with this](https://github.com/microsoft/TypeScript/blob/628bf0ec85be7c58019dc1742e50bc3f97168a5a/src/lib/es2015.proxy.d.ts#L108) by doing:
```ts
interface ProxyConstructor {
    new <T extends object>(target: T, ...): T;
}
```
so maybe we should have:
```py
def proxy[T](target: T, **etc) -> T: ...
```

**Comment by Korijn** [comment]
You are right, I didn't feel like it would be worth the effort while the API was still changing often. But with the recent updates we've done, I am quite sure it won't change much anymore. So this is a good time to add type hints!

Just curious: what are you using observ for? :)

**Comment by ju1ius** [comment]
> Just curious: what are you using observ for? :)

I'm in the process of migrating [an urwid application](https://github.com/ju1ius/clisnips).

It's not really big, but just enough that I start to feel the pain of managing everything with events and callbacks.
