### ISSUE TITLE
Initialize method

### ISSUE THREAD

**Issue by Korijn** [Korijn/observ#115]
After #112 is merged, I want to add an `init` function to the public API that will automatically configure:

* asyncio eager task factory
* register the scheduler with asyncio and/or Qt

All depending on the versions of libs available and if they are already configured or not.

The function should also have an `async` version so it is compatible with `asyncio.run`. It probably just calls the synchronous function.

**Comment by ju1ius** [comment]
> register the scheduler with asyncio and/or Qt

WRT Qt, is it possible to move the dependencies to another poetry group, like it's [done in collagraph](https://github.com/fork-tongue/collagraph/blob/9fb4e9cd937f89badf1330ee52884dbbf718652b/pyproject.toml#L31)?

pyside + pytest-qt + pytest-xvfb == a rather large download, it would be nice to make them optional.

**Comment by Korijn** [comment]
> > register the scheduler with asyncio and/or Qt
> 
> WRT Qt, is it possible to move the dependencies to another poetry group, like it's [done in collagraph](https://github.com/fork-tongue/collagraph/blob/9fb4e9cd937f89badf1330ee52884dbbf718652b/pyproject.toml#L31)?
> 
> pyside + pytest-qt + pytest-xvfb == a rather large download, it would be nice to make them optional.

Yeah we can do that, except in this case, they're not actually dependencies of observ. They're dev only installs. We can still do it if you want but I don't think it matters for end users of the library.

Observ has only one dependency (patchdiff) and we can even make that one optional since it's only used in the Store.

**Comment by ju1ius** [comment]
> Yeah we can do that, except in this case, they're not actually dependencies of observ.

To me that sounds like a good enough reason to move them to an optional group.
Dependencies in the dev group are installed by default, whereas those in optional groups are not.

>  I don't think it matters for end users of the library.

Indeed, but for example if someone finds a bug using the GLib event loop and wants to write an integration test for that, why should he be forced to download the whole QT stack?

🌲

**Comment by Korijn** [comment]
Yeah, for the environment, I love that you bring that up. Let's do it! I have no objections, just wanted to make sure there weren't any misunderstandings.
