### ISSUE TITLE
Watcher type that directly calls callback

### ISSUE THREAD

**Issue by Korijn** [Korijn/observ#80]

**Comment by Korijn** [comment]
@berendkleinhaneveld I can't recall what is different about this request compared to a watcher with `sync=True`, do you?

**Comment by berendkleinhaneveld** [comment]
This is about not evaluating the actual value. There is an implementation in collagraph that shows what's needed.

https://github.com/fork-tongue/collagraph/blob/9fb4e9cd937f89badf1330ee52884dbbf718652b/collagraph/collagraph.py#L29

**Comment by Korijn** [comment]
This seems to be quite an outlandish requirement, possibly not needed even.
