### ISSUE TITLE
Generate watch expressions from (arrays of) watchable objects

### ISSUE THREAD

**Issue by Korijn** [Korijn/observ#81]
See this docs page: https://vuejs.org/api/reactivity-core.html#watch

Vue's watch accepts four types for the first argument:

> * A getter function that returns a value
> * A ref
> * A reactive object
> * ...or an array of the above.

Right now in observ, we only support the first case.

This issue represents the need to implement support for the other three cases. Of course, case number two does not apply to observ since we don't have refs, only reactives.

In other words, allow the following type of constructions:

```python
state = reactive({"text": "Hello, world!})

def on_change(state):
    label.setText(state["text"])

watch(state, on_change)
# instead of watch(lambda: state, on_change, deep=True)
```

**Comment by berendkleinhaneveld** [comment]
At closer inspection, this seems impossible. The value returned from `state["text"]` is all that the `watch` function will receive (a string), so it will never know *how* this value was obtained.

**Comment by Korijn** [comment]
You are right. It can't be supported. Let me clarify and correct:

See this docs page: https://vuejs.org/api/reactivity-core.html#watch

Vue's watch accepts four types for the first argument:

> * A getter function that returns a value
> * A ref
> * A reactive object
> * ...or an array of the above.

So right now in observ, we only support the first case.

With this issue I intended to implement support for the other three cases.

I'll update the top post.

**Comment by berendkleinhaneveld** [comment]
I'll see if I can add the array type watching to #90 some other time
