### ISSUE TITLE
Investigate watcher references in Vue

### ISSUE THREAD

**Issue by Korijn** [Korijn/observ#99]
Vue seems to magically know to keep Watchers alive for a component's lifetime. How does that work?

**Comment by berendkleinhaneveld** [comment]
Could well be that they formalized the life cycle, so they can destroy all related watchers at a specific call, instead of relying on the lifetime of the native javascript object icw garbage collector. But this is just a guess 🙂

**Comment by Korijn** [comment]
I think I've found it, new watchers are attached to the current vue component instance, if the watcher is being created while a vue component is currently active (some part of its lifecycle is running, most commonly creation, mounting and unmounting I guess):

[Watcher constructor](https://github.com/vuejs/vue/blob/81598ea2f3bdbc81ae50f2fa9b9e547efc6b6261/src/core/observer/watcher.ts#L84)

```ts
    if ((this.vm = vm) && isRenderWatcher) {
      vm._watcher = this
    }
```

[Watcher creation](https://github.com/vuejs/vue/blob/81598ea2f3bdbc81ae50f2fa9b9e547efc6b6261/src/v3/apiWatch.ts#L269C44-L269C44)

```ts
  const watcher = new Watcher(currentInstance, getter, noop, {
    lazy: true
  })
```

We don't have that in observ since it's component framework-agnostic. I guess we'd need to expose some kind of hook so collagraph/kolla can subscribe to watcher creation and do the attaching if necessary.

**Comment by Korijn** [comment]
Hmm, no, that doesn't make sense, that's only a single watcher. They probably use that one for detecting when the template needs to be re-rendered (that explains the `isRenderWatcher`)

**Comment by Korijn** [comment]
Found it! https://github.com/vuejs/vue/blob/81598ea2f3bdbc81ae50f2fa9b9e547efc6b6261/src/core/observer/watcher.ts#L74

**Comment by Korijn** [comment]
See #107
